### ISSUE TITLE
Add abstract row operations

### ISSUE THREAD

**Issue by tebe-nigrelli** [quercia-dev/Attimo#10]
Create code leading up to and allowing for addition of a row and other operations:
- Create row in a given category
- Delete row in a category, by index
- Edit row element given index and category
- Run checks on row, return list of pass/fails values
- ...? as necessary

**Comment by tferracina** [comment]
NECESSARY FEATURES:

- optional columns
- error interplay between UI for validation failures
- default values
- uniqueness constraints
