### ISSUE TITLE
defaults.go additions

### ISSUE THREAD

**Issue by tferracina** [quercia-dev/Attimo#13]
`
{Name: "Priority", VariableType: "string", CompletionValue: "{Low,Medium,High,Urgent}", CompletionSort: "frequency", ValueCheck: "default"},
{Name: "Status", VariableType: "string", CompletionValue: "{Not Started,In Progress,On Hold,Completed,Cancelled}", CompletionSort: "last", ValueCheck: "default"},
{Name: "Tags", VariableType: "[]string", CompletionValue: "unique", CompletionSort: "frequency", ValueCheck: "default"},
{Name: "Recurring", VariableType: "string", CompletionValue: "{Daily,Weekly,Monthly,Yearly,No}", CompletionSort: "last", ValueCheck: "default"},
{Name: "Dependencies", VariableType: "[]int", CompletionValue: "no", CompletionSort: "default", ValueCheck: "default"},
{Name: "Budget", VariableType: "float64", CompletionValue: "no", CompletionSort: "default", ValueCheck: "default"},
{Name: "Progress", VariableType: "integer", CompletionValue: "{0,25,50,75,100}", CompletionSort: "last", ValueCheck: "percentage"},
`

**Comment by tebe-nigrelli** [comment]
These seem pretty standard, could be implemented with minimal changes. 
- {Name: "Priority", VariableType: "string", CompletionValue: "{Low,Medium,High,Urgent}", CompletionSort: "frequency", ValueCheck: "default"}, 
- {Name: "Status", VariableType: "string", CompletionValue: "{Not Started,In Progress,On Hold,Completed,Cancelled}", CompletionSort: "last", ValueCheck: "default"}, 
- {Name: "Budget", VariableType: "float64", CompletionValue: "no", CompletionSort: "default", ValueCheck: "default"}, 
- {Name: "Progress", VariableType: "integer", CompletionValue: "{0,25,50,75,100}", CompletionSort: "last", ValueCheck: "percentage"},

Tags would involve parsing existing values over all entries, so each comma separated value is treated as a set of values, whose union serves as the list of autocomplete values.
- {Name: "Tags", VariableType: "[]string", CompletionValue: "unique", CompletionSort: "frequency", ValueCheck: "default"}, 
Give
- {Name: "Recurring", VariableType: "string", CompletionValue: "{Daily,Weekly,Monthly,Yearly,No}", CompletionSort: "last", ValueCheck: "default"}, 

Dependencies could link to other entries, but it would require considering carefully how to jumping to that entry in another table view (requiring a kind of browser history in the gui) and in terms of defining the datatype in terms of the table.
- {Name: "Dependencies", VariableType: "[]int", CompletionValue: "no", CompletionSort: "default", ValueCheck: "default"},
